name: ECR - Build & Push

on:
  workflow_run:
    workflows: ["CI"]   # ← 여기 'CI 워크플로우의 name'을 정확히 넣어줘
    types: [completed]
  workflow_dispatch:

concurrency:
  group: ecr-main
  cancel-in-progress: false

permissions:
  contents: read

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: kickytime-repo

jobs:
  build_and_push:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    env:
      HEAD_SHA: ${{ github.event.workflow_run.head_sha }}

    steps:
      - name: Checkout target commit (from CI)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Configure AWS credentials (Access Keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set TAG from head_sha
        id: tag
        run: echo "TAG=${HEAD_SHA::12}" >> $GITHUB_OUTPUT

      - name: Build & Push image
        run: |
          set -e
          REGISTRY="${{ steps.ecr.outputs.registry }}"
          TAG="${{ steps.tag.outputs.TAG }}"
          IMAGE_URI="$REGISTRY/${{ env.ECR_REPOSITORY }}:$TAG"

          echo "Building $IMAGE_URI (commit=$HEAD_SHA)"
          docker build -t "$IMAGE_URI" .

          echo "Pushing $IMAGE_URI"
          docker push "$IMAGE_URI"

          echo "Tagging latest"
          docker tag "$IMAGE_URI" "$REGISTRY/${{ env.ECR_REPOSITORY }}:latest"
          docker push "$REGISTRY/${{ env.ECR_REPOSITORY }}:latest"

          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_OUTPUT

      - name: Summary
        run: |
          echo "### ✅ ECR Push Completed" >> $GITHUB_STEP_SUMMARY
          echo "- Repo: \`${{ env.ECR_REPOSITORY }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Tag: \`${{ steps.tag.outputs.TAG }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Commit: \`${{ env.HEAD_SHA }}\`" >> $GITHUB_STEP_SUMMARY
