name: ECR - Build & Push

on:
  push:
    branches: [develop]
  workflow_dispatch:

concurrency:
  group: ecr-develop
  cancel-in-progress: false

permissions:
  contents: write   # ⬅️ repository_dispatch에 필요

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: kickytime-repo

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials (Access Keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set TAG from commit SHA
        id: tag
        run: echo "TAG=${GITHUB_SHA::12}" >> $GITHUB_OUTPUT

      - name: Build & Push ARM64 image
        id: build
        run: |
          set -e
          REGISTRY="${{ steps.ecr.outputs.registry }}"
          TAG="${{ steps.tag.outputs.TAG }}"
          IMAGE_URI="$REGISTRY/${{ env.ECR_REPOSITORY }}:$TAG"
          LATEST_URI="$REGISTRY/${{ env.ECR_REPOSITORY }}:latest"

          echo "Building ARM64 image: $IMAGE_URI (commit=${GITHUB_SHA})"
          echo "Branch: ${{ github.ref_name }}"
          
          docker buildx build \
            --platform linux/arm64 \
            --push \
            --tag "$IMAGE_URI" \
            --tag "$LATEST_URI" \
            .

          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_OUTPUT
          echo "Successfully built and pushed ARM64 image"

      - name: Verify ARM64 architecture
        run: |
          REGISTRY="${{ steps.ecr.outputs.registry }}"
          TAG="${{ steps.tag.outputs.TAG }}"
          IMAGE_URI="$REGISTRY/${{ env.ECR_REPOSITORY }}:$TAG"
          
          echo "=== Verifying image architecture ==="
          docker manifest inspect "$IMAGE_URI" | grep -A 10 '"architecture"'
          
          ARCH=$(docker manifest inspect "$IMAGE_URI" | jq -r '.manifests[0].platform.architecture // .architecture')
          if [ "$ARCH" = "arm64" ]; then
            echo "✅ Confirmed: Image is ARM64"
          else
            echo "❌ Error: Image architecture is $ARCH, expected arm64"
            exit 1
          fi

      # ✅ 여기서 ECS 배포 트리거(repository_dispatch)를 전송
      - name: Trigger ECS Deploy via repository_dispatch
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const image_uri = `${{ steps.build.outputs.IMAGE_URI }}`;
            const tag = `${{ steps.tag.outputs.TAG }}`;
            const branch = `${{ github.ref_name }}`;
            const sha = `${{ github.sha }}`;

            core.info(`Dispatching deploy-ecs with image_uri=${image_uri}, tag=${tag}, branch=${branch}, sha=${sha}`);

            await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'deploy-ecs',
              client_payload: {
                image_uri,
                tag,
                branch,
                sha
              }
            });

      - name: Summary
        run: |
          echo "### ✅ ECR Push Completed (ARM64)" >> $GITHUB_STEP_SUMMARY
          echo "- Repo: \`${{ env.ECR_REPOSITORY }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Tag: \`${{ steps.tag.outputs.TAG }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Commit: \`${GITHUB_SHA}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Branch: \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Platform: \`linux/arm64\`" >> $GITHUB_STEP_SUMMARY
          echo "- Image: \`${{ steps.build.outputs.IMAGE_URI }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Triggered: \`repository_dispatch: deploy-ecs\`" >> $GITHUB_STEP_SUMMARY
